%processData2
%processData
%Processing 200 files generated by HPC cluster by running the Simulation
%200 times

close all
clear
nFiles = 500;
densityBL = [0.01,0.1,0.2,0.5,0.65];
densityAP = (1:.5:10)/10^4;
for i=1:nFiles
    data(:,:,i)=csvread(strcat('Data2/output',int2str(i),'.csv'));
end
data(isnan(data))=0;
meanVal = reshape(mean(data,3),6,length(densityBL),length(densityAP));
%The 6 columns are [avgFreq,avgDur,probAllBl,th_freqBl,th_durBl,th_probAllBl];
avgFreq = squeeze(meanVal(1,:,:));
avgDur= squeeze(meanVal(2,:,:));
probAllBl= squeeze(meanVal(3,:,:));
th_freqBl= squeeze(meanVal(4,:,:));
th_durBl= squeeze(meanVal(5,:,:));
th_probAllBl= squeeze(meanVal(6,:,:));

color = {'r','g','b','m','k'};
h=figure(1);
grid on;
for j=1:5
semilogy(densityAP*10^4, probAllBl(j,:),'color',color{j},'LineWidth',2)
hold on;
end
for j=1:5
semilogy(densityAP*10^4, th_probAllBl(j,:),'color',color{j},'LineStyle','--','LineWidth',2)
hold on;
end
ylim([10^-4,1])
g=legend('\rho_B=0.01 bl/m^2','\rho_B=0.1 bl/m^2','\rho_B=0.2 bl/m^2',...
    '\rho_B=0.5 bl/m^2','\rho_B=0.65 bl/m^2' );
set(g,'fontsize',13)
xlabel('AP Density \lambda_T (x 100/km^2)', 'fontsize',13)
ylabel('Prob all APs blocked within 100m','fontsize',13)
set(h,'Units','Inches');
pos = get(h,'Position');
set(h,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
print(h,[pwd '/figures/prob_all_bl_new.pdf'],'-dpdf','-r0')
print(h,[pwd '/figures/prob_all_bl_new.png'],'-dpng','-r0')

h=figure(2);
grid on;
for j=1:5
semilogy(densityAP*10^4, avgFreq(j,:),'color',color{j},'LineWidth',2)
hold on;
end
for j=1:5
semilogy(densityAP*10^4, th_freqBl(j,:),'color',color{j},'LineStyle','--','LineWidth',2)
hold on;
end
ylim([10^-4,1])
g=legend('\rho_B=0.01 bl/m^2','\rho_B=0.1 bl/m^2','\rho_B=0.2 bl/m^2',...
    '\rho_B=0.5 bl/m^2','\rho_B=0.65 bl/m^2' );
set(g,'fontsize',13)
xlabel('AP Density \lambda_T (x 100/km^2)', 'fontsize',13)
ylabel('Average frequency of all APs blockage','fontsize',13)
set(h,'Units','Inches');
pos = get(h,'Position');
set(h,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
print(h,[pwd '/figures/avg_freq_new.pdf'],'-dpdf','-r0')
print(h,[pwd '/figures/avg_freq_new.png'],'-dpng','-r0')

h=figure(3);
grid on;
for j=1:5
semilogy(densityAP*10^4, avgDur(j,:),'color',color{j},'LineWidth',2)
hold on;
end
for j=1:5
semilogy(densityAP*10^4, th_durBl(j,:),'color',color{j},'LineStyle','--','LineWidth',2)
hold on;
end
ylim([10^-3,1])
g=legend('\rho_B=0.01 bl/m^2','\rho_B=0.1 bl/m^2','\rho_B=0.2 bl/m^2',...
    '\rho_B=0.5 bl/m^2','\rho_B=0.65 bl/m^2' );
set(g,'fontsize',13)
xlabel('AP Density \lambda_T (x 100/km^2)', 'fontsize',13)
ylabel('Average blockage duration of all APs','fontsize',13)
set(h,'Units','Inches');
pos = get(h,'Position');
set(h,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
print(h,[pwd '/figures/avg_dur_new.pdf'],'-dpdf','-r0')
print(h,[pwd '/figures/avg_dur_new.png'],'-dpng','-r0')

